name: GetTopWordsFromWebsite

on:
  workflow_dispatch:
    inputs:
      Domain:
        description: 'Please enter the URL'
        default: 'https://example.com'
        required: true
        type: string
        
      number:
        description: 'Number of Words to Pull back'
        default: '30'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  GetTopWordsFromWebsite:
    runs-on: ubuntu-latest
    steps:
    # Set up Python environment
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: 'pip' 
    - run: pip install -r requirements.txt
        
    - name: GetTopWordsFromWebsite
      run: python GetTopWordsFromWebsite.py --domaininput ${{ github.event.inputs.Domain }} --NoOfWords ${{ github.event.inputs.number }}
